# Generated by Codex on 2024-06-01
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0002_add_status_description'),
        ('Workforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='invoice.invoice')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Workforce.workforce')),
            ],
        ),
    ]
