
services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypostgrespass
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /home/helpers/Swifthelpers/postgres-data:/var/lib/postgresql/data
    command:
      -c port=5434
      -c listen_addresses=*
  backend:
    image: django-backend
    container_name: django-backend
    restart: unless-stopped
    env_file:
      - SwiftLink/.env
    network_mode: host
    depends_on:
      - postgres-db
    volumes:
      - static_volume:/app/static

  frontend:
    image: angular-frontend
    container_name: angular-frontend
    restart: unless-stopped
    network_mode: host

volumes:
  static_volume:
