version: '3.8'

services:
  backend:
    build: ./SwiftLink
    container_name: django-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - static_volume:/app/static
    env_file:
      - SwiftLink/.env

  frontend:
    build: ./frontend
    container_name: angular-frontend
    restart: unless-stopped
    ports:
      - "80:80"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 30

volumes:
  static_volume:
