version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
    env_file:
      - backend/.env

  frontend:
    build: ./frontend
    container_name: angular-frontend
    restart: unless-stopped
    ports:
      - "80:80"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 30

volumes:
  static_volume:
