services:
  backend:
    image: django-backend
    container_name: django-backend
    network_mode: host
    restart: unless-stopped
    volumes:
      - static_volume:/app/static
    env_file:
      - SwiftLink/.env

  frontend:
    image: angular-frontend
    container_name: angular-frontend
    network_mode: host
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 300

volumes:
  static_volume:
