# Generated by Django 5.1.6 on 2025-03-10 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JobRessources', '0001_initial'),
        ('Ref_Entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('serviceTypeID', models.AutoField(primary_key=True, serialize=False, verbose_name='Service Type ID')),
                ('serviceName', models.CharField(max_length=255, verbose_name='Service Name')),
                ('serviceDescription', models.TextField(verbose_name='Service Description')),
                ('manpower', models.IntegerField(default=1, verbose_name='Manpower Required')),
                ('manpowerRate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Manpower Rate')),
                ('jobResourcesRate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Job Resources Rate')),
                ('division', models.CharField(choices=[('PROS', 'Professionals'), ('HELPER', 'Helpers'), ('OTHER', 'Other')], max_length=10, verbose_name='Division')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('fixedServiceRate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fixed Service Rate')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ref_Entity.ref_entity', verbose_name='Related Entity')),
                ('jobResources', models.ManyToManyField(blank=True, related_name='service_types', to='JobRessources.jobresources', verbose_name='Job Resources')),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
            },
        ),
    ]
