# Generated by Django 5.1.6 on 2025-03-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ref_User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref_user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ref_user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
