# Generated by Django 5.1.6 on 2025-05-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ref_User', '0002_alter_ref_user_first_name_alter_ref_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref_user',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='user_profiles/', verbose_name='Profile Image'),
        ),
    ]
