# Generated by Django 5.1.6 on 2025-05-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ref_User', '0003_ref_user_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref_user',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
