# Generated by Django 5.2.3 on 2025-06-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_conversation_pending_order_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
