# Generated by Django 5.2.3 on 2025-06-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_message_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="system",
            field=models.BooleanField(default=False),
        ),
    ]
