# Generated by Django 5.1.6 on 2025-03-10 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ref_Entity', '0001_initial'),
        ('Ref_User', '0001_initial'),
        ('ServiceType', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkForce',
            fields=[
                ('UserId', models.OneToOneField(limit_choices_to={'role': 'WORKFORCE'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('dateOfBirth', models.DateField()),
                ('socialSecurityNumber', models.CharField(max_length=20)),
                ('skills', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('availability', models.JSONField()),
                ('hourlyRatebyService', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixedRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driverLicence', models.CharField(max_length=50)),
                ('driverLicenceExpiry', models.DateField()),
                ('credentials', models.TextField()),
                ('credentialsExpiry', models.DateField()),
                ('training', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('workForceType', models.CharField(choices=[('Office Admin', 'Office Admin'), ('Operation Supervisor', 'Operation Supervisor'), ('Team Lead', 'Team Lead'), ('Employee', 'Employee'), ('Professional Helper', 'Professional Helper'), ('General Helper', 'General Helper'), ('Expert', 'Expert')], max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('entityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ref_Entity.ref_entity')),
                ('workCategory', models.ManyToManyField(to='ServiceType.servicetype')),
            ],
        ),
    ]
