# Generated by Django 5.1.6 on 2025-03-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workforce', '0002_remove_workforce_firstname_remove_workforce_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforce',
            name='credentials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workforce',
            name='credentialsExpiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workforce',
            name='driverLicence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workforce',
            name='driverLicenceExpiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workforce',
            name='fixedRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='workforce',
            name='hourlyRatebyService',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='workforce',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='workforce',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workforce',
            name='training',
            field=models.TextField(blank=True, null=True),
        ),
    ]
