# Generated by Django 5.1.6 on 2025-05-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workforce', '0003_alter_workforce_credentials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforce',
            name='acces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workforce',
            name='professionnelemail',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
