# Generated by Django 5.1.6 on 2025-05-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workforce', '0004_workforce_acces_workforce_professionnelemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforce',
            name='dateOfBirth',
            field=models.DateField(blank=True),
        ),
    ]
