# Generated by Django 5.1.6 on 2025-05-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workforce', '0005_alter_workforce_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforce',
            name='availability',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='workforce',
            name='socialSecurityNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
