# Generated by Django 5.1.6 on 2025-05-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workforce', '0006_alter_workforce_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforce',
            name='careerExpectations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforce',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workforce',
            name='clientChargeRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workforce',
            name='consumablesFee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workforce',
            name='country',
            field=models.CharField(default='Canada', max_length=100),
        ),
        migrations.AddField(
            model_name='workforce',
            name='driverLicenceFile',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='workforce',
            name='platformFeeRate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='workforce',
            name='postalCode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='workforce',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workforce',
            name='referralSource',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workforce',
            name='securityFundRate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='workforce',
            name='wantsUpdates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workforce',
            name='wcbFile',
            field=models.FileField(blank=True, null=True, upload_to='wcb_clearances/'),
        ),
        migrations.AddField(
            model_name='workforce',
            name='wcbNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
