# Generated by Django 5.1.6 on 2025-05-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workforce', '0007_workforce_careerexpectations_workforce_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforce',
            name='driverLicenceClass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workforce',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='workforce',
            name='yearsOfExperience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
