# Generated by Django 5.1.6 on 2025-05-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workforce', '0008_workforce_driverlicenceclass_workforce_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforce',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
