# Generated by Django 5.1.6 on 2025-05-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workforce', '0009_alter_workforce_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforce',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
