# Generated by Django 5.1.6 on 2025-03-10 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ref_Entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefCountry',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=255, unique=True)),
                ('country_code', models.CharField(max_length=10, unique=True)),
                ('country_dial_code', models.CharField(max_length=10)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ref_Entity.ref_entity')),
            ],
        ),
    ]
