# Generated by Django 5.1.6 on 2025-04-29 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_helper',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='notif_helper', to=settings.AUTH_USER_MODEL),
        ),
    ]
