# Generated by Django 5.1.6 on 2025-05-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0002_alter_order_assignedto_alter_order_executiondate_and_more'),
        ('Workforce', '0003_alter_workforce_credentials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('serviceType', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('baseAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extras', models.JSONField(blank=True, default=list)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('sentToClient', models.BooleanField(default=False)),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Workforce.workforce')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='Order.order')),
            ],
        ),
    ]
