# Generated by Django 5.1.6 on 2025-03-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobResources',
            fields=[
                ('jobResourcesID', models.AutoField(primary_key=True, serialize=False, verbose_name='Job Resource ID')),
                ('name', models.CharField(max_length=255, verbose_name='Resource Name')),
                ('category', models.CharField(choices=[('EQUIPMENT', 'Equipment'), ('MATERIAL', 'Material'), ('PART', 'Part')], max_length=10, verbose_name='Category')),
                ('technicalSpecification', models.TextField(verbose_name='Technical Specification')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('jobResourceRate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Job Resource Rate')),
                ('chargeableToClient', models.BooleanField(default=True, verbose_name='Chargeable to Client')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('linkedToService', models.BooleanField(default=False, verbose_name='Linked to Service')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Job Resource',
                'verbose_name_plural': 'Job Resources',
            },
        ),
    ]
